# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml hatchling.toml* ./
COPY src ./src
COPY README.md LICENSE CHANGELOG.rst ./

# Install package
RUN pip install --no-cache-dir .

# Ensure output is not buffered
ENV PYTHONUNBUFFERED=1

# Default command to start the MCP server
CMD ["card_magic_mcp"]
